"""Create Reviews

Revision ID: f63ee7622d1d
Revises: 07f84aeb2e4e
Create Date: 2024-05-22 19:24:49.019107

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f63ee7622d1d"
down_revision = "07f84aeb2e4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], name=op.f("fk_Reviews_course_id_courses")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_Reviews_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Reviews")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    # ### end Alembic commands ###
