version: '3'

services:
  web:
    build: ./app
    ports:
      - "8084:5000"
    networks:
      - mynetwork2
    depends_on:
      - db

  db:
    build: ./app/db/
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab5
    networks:
      - mynetwork2
networks:
  mynetwork2: