version: '3'

services:
  web:
    build: ./app
    ports:
      - "8085:5000"

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab6
    networks:
      - mynetwork